name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - '[0-9]+.x'
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Deps
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint:ci

      - name: Build
        run: |
          npm run build

      - name: Tests
        run: |
          npm run test:ci

  automerge:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
